import { mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import { type Finding, validateTheme } from "./contract.js";
import { themes } from "./index.js";
import { renderThemeCss, renderThemeJson } from "./render.js";

const DIST = dirname(fileURLToPath(import.meta.url));

export function outputs(): Record<string, string> {
  const out: Record<string, string> = {};
  const contract: string[] = [
    "# Theme contract record",
    "",
    "Generated by `packages/themes/src/build.ts`. Every theme is validated against the",
    "contract: six slots plus enamel and object radius, each pairing measured with the",
    "WCAG 2.x formula. A failing row fails `bun run check`.",
    "",
  ];
  for (const theme of Object.values(themes)) {
    out[`${theme.id}.css`] = renderThemeCss(theme);
    out[`${theme.id}.unlayered.css`] = renderThemeCss(theme, { layer: false });
    out[`${theme.id}.json`] = renderThemeJson(theme);
    const findings = validateTheme(theme);
    contract.push(
      `## ${theme.name} (\`${theme.id}\`, ${theme.status})`,
      "",
      "| Env | Rule | Colour | On | Ratio | Bar | Result |",
      "|---|---|---|---|---:|---:|---|",
    );
    for (const f of findings)
      contract.push(
        `| ${f.env} | ${f.rule} | ${f.fg} | ${f.on} | ${f.ratio === null ? "—" : f.ratio.toFixed(2)} | ${f.bar} | ${f.passes ? "pass" : "**FAIL**"} |`,
      );
    contract.push("");
  }
  out["CONTRACT.md"] = `${contract.join("\n")}\n`;
  return out;
}

export function allFindings(): Finding[] {
  return Object.values(themes).flatMap((t) => validateTheme(t));
}

function main(): void {
  const check = process.argv.includes("--check");
  const files = outputs();
  const failures = allFindings().filter((f) => !f.passes);
  let stale = 0;
  mkdirSync(DIST, { recursive: true });
  for (const [name, content] of Object.entries(files)) {
    const path = join(DIST, name);
    if (check) {
      let current = "";
      try {
        current = readFileSync(path, "utf8");
      } catch {
        current = "";
      }
      if (current !== content) {
        stale += 1;
        console.error(`stale: ${name}`);
      }
    } else writeFileSync(path, content);
  }
  for (const f of failures)
    console.error(
      `contract FAIL: ${f.rule} (${f.env}) ${f.fg} on ${f.on}: ${f.ratio ?? "—"} < ${f.bar}`,
    );
  console.log(
    `${Object.keys(themes).length} themes, ${allFindings().length} contract pairings, ${failures.length} failing${check ? `, ${stale} stale outputs` : ""}.`,
  );
  if (failures.length > 0 || stale > 0) process.exitCode = 1;
}

if (process.argv[1] && fileURLToPath(import.meta.url) === process.argv[1]) main();
