/**
 * Render the token tree to CSS custom properties. Day is the base; night sits on
 * `[data-ww-env="night"]` and follows the system under `[data-ww-env="auto"]`.
 * Adapters for frameworks that invert the default (Starlight) do so in their own file.
 */
import {
  breakpoints,
  code,
  depth,
  type Env,
  material,
  motion,
  radius,
  semanticColor,
  size,
  space,
  themeSlots,
  type,
  wonderWagonDefaults,
} from "./tokens.js";

/**
 * Day is the base on :root. The environment attribute works on any element, not
 * only the root: a dark panel in day sets `data-ww-env="night"` on itself and every
 * semantic token inside it — ink, focus, enamel — re-scopes to the night values.
 * That is how a component re-scopes without carrying a single literal.
 */
export const ENV_SELECTOR: Readonly<Record<Env, string>> = {
  day: ':root, [data-ww-env="day"]',
  night: '[data-ww-env="night"]',
};
export const AUTO_SELECTOR = '[data-ww-env="auto"]';

/** The full semantic map for one environment, with the Wonder Wagon defaults in the theme slots. */
export function semanticValues(env: Env): Record<string, string> {
  const out: Record<string, string> = {};
  for (const [name, token] of Object.entries(semanticColor)) out[name] = token.value[env];
  for (const slot of themeSlots) out[slot] = wonderWagonDefaults[slot][env];
  return out;
}

export function declarations(map: Record<string, string>, prefix = "--ww-"): string[] {
  return Object.entries(map).map(([name, value]) => `  ${prefix}${name}: ${value};`);
}

function envBlock(env: Env): string[] {
  const lines = [`  color-scheme: ${env === "day" ? "light" : "dark"};`];
  lines.push(...declarations(semanticValues(env)));
  lines.push(`  --ww-m-enamel: ${wonderWagonDefaults.enamel[env]};`);
  lines.push(`  --ww-depth-quiet: ${depth.quiet.value[env]};`);
  for (const [name, value] of Object.entries(code)) lines.push(`  --ww-${name}: ${value[env]};`);
  return lines;
}

function staticBlock(): string[] {
  const lines: string[] = [];
  for (const [name, value] of Object.entries(material)) lines.push(`  --ww-m-${name}: ${value};`);
  for (const [name, token] of Object.entries(depth)) {
    if (name === "quiet") continue;
    lines.push(`  --ww-depth-${name}: ${token.value as string};`);
  }
  for (const [name, token] of Object.entries(type)) lines.push(`  --ww-${name}: ${token.value};`);
  for (const [name, value] of Object.entries(space)) lines.push(`  --ww-${name}: ${value};`);
  for (const [name, value] of Object.entries(size)) lines.push(`  --ww-${name}: ${value};`);
  for (const [name, value] of Object.entries(radius)) lines.push(`  --ww-${name}: ${value};`);
  lines.push(`  --ww-radius-object: ${wonderWagonDefaults.radiusObject};`);
  for (const [name, value] of Object.entries(motion)) lines.push(`  --ww-${name}: ${value};`);
  return lines;
}

export function renderTokensCss(options: { layer: boolean }): string {
  const day = [...envBlock("day"), ...staticBlock()];
  const night = envBlock("night");
  const body = [
    `/* @wonder-wagon/tokens — generated by packages/tokens/src/build.ts. Do not edit. */`,
    `${ENV_SELECTOR.day} {`,
    ...day,
    "}",
    `${ENV_SELECTOR.night} {`,
    ...night,
    "}",
    "@media (prefers-color-scheme: dark) {",
    `  ${AUTO_SELECTOR} {`,
    ...night.map((l) => `  ${l}`),
    "  }",
    "}",
    "",
    "/* Reduced motion: every animation has a static equivalent. 1ms rather than none so",
    "   transitionend still fires for components that wait on it. */",
    "@media (prefers-reduced-motion: reduce) {",
    "  :root { --ww-motion-throw: 1ms; --ww-motion-reveal: 1ms; }",
    "}",
    "",
    `/* Breakpoints (not custom properties): sm ${breakpoints.sm} · md ${breakpoints.md} · lg ${breakpoints.lg} · xl ${breakpoints.xl} */`,
  ];
  if (!options.layer) return `${body.join("\n")}\n`;
  return `@layer ww.tokens, ww.base, ww.components, ww.theme;\n@layer ww.tokens {\n${body.map((l) => (l ? `  ${l}` : l)).join("\n")}\n}\n`;
}

/** A theme-shaped CSS string that consumers inline into a generated document (Pathfinder's renderer pattern). */
export function cssText(): string {
  return renderTokensCss({ layer: false });
}
