// Assemble the library's stylesheets from the hand-authored component CSS.
// Components never import CSS from JavaScript; consumers load these files.
import { mkdirSync, readdirSync, readFileSync, writeFileSync } from "node:fs";
import { join } from "node:path";

const root = new URL("..", import.meta.url).pathname;
const src = join(root, "src");
const dist = join(root, "dist");
mkdirSync(dist, { recursive: true });

const kebab = (s) => s.replace(/([a-z0-9])([A-Z])/g, "$1-$2").toLowerCase();
const base = readFileSync(join(src, "styles", "base.css"), "utf8");
const components = readdirSync(join(src, "components"), { withFileTypes: true })
  .filter((d) => d.isDirectory())
  .map((d) => d.name)
  .sort();

const header = "/* @wonder-wagon/ui — generated by scripts/build-css.mjs. Do not edit. */\n";
const indent = (css) =>
  css
    .trim()
    .split("\n")
    .map((l) => (l ? `  ${l}` : l))
    .join("\n");
let all = "";
for (const name of components) {
  const css = readFileSync(join(src, "components", name, `${name}.css`), "utf8");
  all += `${css.trim()}\n\n`;
  writeFileSync(
    join(dist, `${kebab(name)}.css`),
    `${header}@layer ww.components {\n${indent(css)}\n}\n`,
  );
}
writeFileSync(
  join(dist, "styles.css"),
  `${header}@layer ww.base {\n${indent(base)}\n}\n@layer ww.components {\n${indent(all)}\n}\n`,
);
writeFileSync(join(dist, "styles.unlayered.css"), `${header}${base.trim()}\n\n${all.trim()}\n`);
console.log(`css: ${components.length} components → dist/styles.css`);
