/**
 * A product that prints rather than renders — Forge, Pathfinder's installer — takes
 * one identity colour from its theme and leaves severity to the terminal's own
 * eight colours, which render identically everywhere (Pathfinder's ruling U5).
 * The result is generated once into the product and committed, so the product's
 * runtime stays dependency-free and its bytes deterministic.
 */
import { type Env, brand as familyBrand } from "@wonder-wagon/tokens";
import { type TerminalPaint, terminalPaint } from "@wonder-wagon/tokens/terminal";
import type { ProductTheme } from "../contract.js";

export type Severity = "ok" | "info" | "warn" | "bad";
export type AnsiName = "green" | "cyan" | "yellow" | "red";

export interface TerminalIdentity {
  readonly theme: ProductTheme["id"];
  readonly name: string;
  /** e.g. FG-047: the product's serial and the family maker. */
  readonly serial: string;
  /** Which environment's signal value was chosen. Terminals are mostly dark; the night value is the default. */
  readonly env: Env;
  readonly brand: TerminalPaint;
  /** Severity is never a brand colour: standard ANSI names the product maps to its own SGR codes. */
  readonly severity: Readonly<Record<Severity, AnsiName>>;
}

export function terminalIdentity(theme: ProductTheme, env: Env = "night"): TerminalIdentity {
  return {
    theme: theme.id,
    name: theme.name,
    serial: `${theme.serial}-${familyBrand.maker}`,
    env,
    brand: terminalPaint(theme.signal[env]),
    severity: { ok: "green", info: "cyan", warn: "yellow", bad: "red" },
  };
}

/**
 * Source text for a generated TypeScript module the product commits. Contains only
 * literals, a provenance header with the package version (never a date), and a hash
 * of the values so a `--check` can tell "edited by hand" from "regenerated".
 */
export function renderTerminalModule(
  theme: ProductTheme,
  options: { packageVersion: string; env?: Env },
): string {
  const id = terminalIdentity(theme, options.env ?? "night");
  const values = JSON.stringify({ brand: id.brand, serial: id.serial, severity: id.severity });
  const hash = fnv1a(values);
  const esc = (s: string) => JSON.stringify(s);
  return [
    "// GENERATED by @wonder-wagon/themes/adapters/terminal — do not edit.",
    `// Source: @wonder-wagon/themes@${options.packageVersion}, theme ${esc(theme.id)}, ${id.env} signal ${id.brand.hex}.`,
    `// Regenerate with the product's sync script; verify with its --check. Values hash: ${hash}.`,
    "",
    "/** The product's serial and the family maker's mark: stated once, printed small. */",
    `export const SERIAL = ${esc(id.serial)};`,
    "",
    "/** The one identity colour, in every alphabet a terminal speaks. Severity never uses it. */",
    "export const BRAND = Object.freeze({",
    `  hex: ${esc(id.brand.hex)},`,
    `  truecolor: ${esc(id.brand.truecolor)},`,
    `  ansi256: ${esc(id.brand.ansi256)},`,
    `  ansi16: ${esc(id.brand.ansi16)},`,
    "});",
    "",
    "/** Severity maps to the terminal's own colours, which render the same everywhere. */",
    "export const SEVERITY = Object.freeze({",
    ...(Object.entries(id.severity) as Array<[Severity, AnsiName]>).map(
      ([k, v]) => `  ${k}: ${esc(v)},`,
    ),
    "});",
    "",
    `export const VALUES_HASH = ${esc(hash)};`,
    "",
  ].join("\n");
}

function fnv1a(input: string): string {
  let h = 0x811c9dc5;
  for (let i = 0; i < input.length; i++) {
    h ^= input.charCodeAt(i);
    h = Math.imul(h, 0x01000193) >>> 0;
  }
  return h.toString(16).padStart(8, "0");
}
